using AVCodecID = CodecID;
using AVPixelFormat = PixelFormat;
#define AV_CODEC_ID_MPEG2VIDEO CODEC_ID_MPEG2VIDEO
#define AV_CODEC_ID_MPEG1VIDEO CODEC_ID_MPEG1VIDEO
#define AV_CODEC_ID_DVVIDEO CODEC_ID_DVVIDEO
#define AV_CODEC_ID_MPEG2TS CODEC_ID_MPEG2TS
#define AV_CODEC_ID_MJPEG CODEC_ID_MJPEG
#define AV_CODEC_ID_H264 CODEC_ID_H264
#define AV_CODEC_ID_THEORA CODEC_ID_THEORA
#define AV_CODEC_ID_VP8 CODEC_ID_VP8
#define AV_CODEC_ID_PCM_S16LE CODEC_ID_PCM_S16LE
#define AV_CODEC_ID_NONE CODEC_ID_NONE


#define AV_PIX_FMT_RGB8 	PIX_FMT_RGB8
#define AV_PIX_FMT_BGR8 	PIX_FMT_BGR8
#define AV_PIX_FMT_RGB555 	PIX_FMT_RGB555
#define AV_PIX_FMT_RGB565 	PIX_FMT_RGB565
#define AV_PIX_FMT_BGR555	PIX_FMT_BGR555
#define AV_PIX_FMT_BGR565	PIX_FMT_BGR565
#define AV_PIX_FMT_RGB24	PIX_FMT_RGB24
#define AV_PIX_FMT_BGR24	PIX_FMT_BGR24
#define AV_PIX_FMT_RGBA		PIX_FMT_RGBA
#define AV_PIX_FMT_ARGB		PIX_FMT_ARGB
#define AV_PIX_FMT_BGRA		PIX_FMT_BGRA
#define AV_PIX_FMT_ABGR		PIX_FMT_ABGR
#define AV_PIX_FMT_RGB48	PIX_FMT_RGB48
#define AV_PIX_FMT_BGR48	PIX_FMT_BGR48
#ifdef PIX_FMT_RGBA64
#define AV_PIX_FMT_RGBA64	PIX_FMT_RGBA64
#endif
#ifdef PIX_FMT_BGRA64
#define AV_PIX_FMT_BGRA64	PIX_FMT_BGRA64
#endif
#define AV_PIX_FMT_GRAY8	PIX_FMT_GRAY8
#define AV_PIX_FMT_GRAY16	PIX_FMT_GRAY16
#define AV_PIX_FMT_YUV420P	PIX_FMT_YUV420P
#define AV_PIX_FMT_YUV422P	PIX_FMT_YUV422P
#define AV_PIX_FMT_YUV444P	PIX_FMT_YUV444P
#define AV_PIX_FMT_YUYV422	PIX_FMT_YUYV422
#define AV_PIX_FMT_UYVY422	PIX_FMT_UYVY422
#define AV_PIX_FMT_YUV411P	PIX_FMT_YUV411P
#define AV_PIX_FMT_YUV422P10LE	PIX_FMT_YUV422P10LE
#define AV_PIX_FMT_YUVJ420P	PIX_FMT_YUVJ420P
#define AV_PIX_FMT_YUVJ422P	PIX_FMT_YUVJ422P
#define AV_PIX_FMT_YUVJ444P	PIX_FMT_YUVJ444P
#define AV_PIX_FMT_NONE		PIX_FMT_NONE
